default_polling_rate: 1000
game_polling_rate: 2000
check_interval: 2s
steam:
  install_path: c:\program files (x86)\steam
  libraries:
    - path: c:\program files (x86)\steam
      label: Main
    - path: F:\\SteamLibrary
      label: Drive F
  last_scan: 2025-09-05T14:25:54.8095358-03:00
detected_games:
  - name: Abiotic Factor
    app_id: "427410"
    executable: AbioticFactor.exe
    install_path: c:\program files (x86)\steam\steamapps\common\AbioticFactor
    library: Main
    size_mb: 5624
  - name: Aimlabs
    app_id: "714010"
    executable: AimLabLinksHandler.exe
    install_path: F:\SteamLibrary\steamapps\common\Aim Lab
    library: Drive F
    size_mb: 17247
  - name: Battlefield™ 2042
    app_id: "1517290"
    executable: BF2042.exe
    install_path: F:\SteamLibrary\steamapps\common\Battlefield 2042
    library: Drive F
    size_mb: 105020
  - name: "Hunt: Showdown 1896"
    app_id: "594650"
    executable: hunt.exe
    install_path: F:\SteamLibrary\steamapps\common\Hunt Showdown 1896
    library: Drive F
    size_mb: 78514
  - name: The Last of Us™ Part II Remastered
    app_id: "2531310"
    executable: launcher.exe
    install_path: F:\SteamLibrary\steamapps\common\The Last of Us Part II
    library: Drive F
    size_mb: 118798
